version: '3.6'

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: HIS_db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data: {}
